Collection of helper scripts for OceanLotus
===========================================

This repository contains scripts to help analysing OceanLotus' macOS samples.

As described in
https://www.welivesecurity.com/2019/04/09/oceanlotus-macos-malware-update/[ESET
article] the strings are encrypted with AES-256 CBC. Some strings are also
encoded in base64 using a custom alphabet.

The script `OL_OSX_decryptor.py` is a based on a generic way to retrieve a
function arguments as well as their assignment. Its core relies on a hook of the
`function` window. This means that by right-clicking the desired function in the
`function` window, there will be an additional element. When clicking this
element, the script will try to retrieve the arguments of this function and in
this case: the data, the size of the data, the key, the size of key and the
boolean value determining if the data is encoded in base64.

In order for the script to work correctly, the custom alphabet used by the
base64 decode function should be set (it is already set by default) and the
global variable holding the size of the key should be defined as a DWORD.

By default, the script displays the decrypted strings in the `output` window but
you can uncomment the call to the function `add_comment` to make it add the
decrypted strings as comments to the cross-reference of the function.

If you want to just test the script, it is highly recommended to use the
`Script command...` functionality (under File).
