= Linux/Moose Targeted Vendors
// Olivier Bilodeau <bilodeau@eset.com>
// Copyright (C) 2015 ESET

This is an attempt at identifying hardware make and model that is being
targeted by the Linux/Moose threat.

This is released as part of our research on this embedded Linux
threat. The full report is available here:
http://www.welivesecurity.com/wp-content/uploads/2015/05/Dissecting-LinuxMoose.pdf

If you see a vendor of a device you own and can legally test, please validate
if the requirements for a Linux/Moose infection are met and
mailto:github@eset.com[let us know] of your findings.

NOTE: These lists are created as a community effort, we could not
      personally validate all these devices due to time constraints and
      hardware access.

== Moose Requirements

.Linux-based System
Linux/Moose requires a Linux-based system because of its dependency on
http://www.uclibc.org/[µClibc], a popular C library for embedded systems.
Plenty of embedded systems are now running Linux -- from consumer routers to
carrier-grade network gear through Internet of Things (IoT) appliances.

.Telnet access
For automated infection, access must be obtained via the Telnet protocol on
port 23. Telnet access should be granted with no authentication or
weak/default usernames and passwords listed
http://www.urtech.ca/2011/12/default-passwords/[in this list]. This list is
provided by a command and control server and can be updated by the operators.

// TODO
// You can use our TODO:[Telnet testing tool] in order to validate this aspect.

.Shell access
Devices must have some sort of text interface. Menu-driven text user
interfaces are not supported. If the Telnet connection lead to a root shell
`#` directly then the infection process starts. Otherwise the malware will try
to gain access to the root shell by issuing a `sh` command.

On some devices this type of access is hidden behind another set of
credentials or tech-support secret passwords. Moose doesn't currently target
these environments.

== Targeted Vendors

Some affected devices are easier to identify than others. For instance: upon
launch, the malware checks whether the file `/home/hik/start.sh` exists on disk.
This path is usually associated with Hik Vision DVRs which
http://www.hikvision.com/europe/Press-Release-details.asp?id=2692[are being
targeted by embedded malware]. Another means of identification is to look at what routers
support the methods used to perform <<dns-hijack,DNS Hijacking>>. Last but not
least is to look at what devices are affected by the threats that Linux/Moose
<<killing,tries to eliminate>> when it runs. Here is a list of vendors we know
are being targeted:

.Targeted Vendors List
____
Actiontec, Hik Vision, Netgear, Synology, TP-Link, ZyXEL, Zhone
____

== Potentially Targeted Vendors

We have cross-referenced the list of
http://www.urtech.ca/2011/12/default-passwords/[usernames and passwords that
Moose uses] in order to spread with a list of vendors known to have these as default
credentials and confirmed that some of their products have Telnet access
enabled. Here is the list of potentially targeted vendors we've come up using
this methodology:

.Network Equipment Vendors
____
3Com, Alcatel-Lucent, Allied Telesis, Avaya, Belkin,
Brocade, Buffalo, Celerity, Cisco, D-link, Enterasys, Hewlett-Packard, Huawei,
Linksys, Mikrotik, Netgear, Meridian, Nortel, SpeedStream, Thomson, TP-Link,
Zhone, ZyXEL
____

.Appliances Vendors
____
APC, Brother, Konica/Minolta, Kyocera, Microplex, Ricoh, Toshiba, Xerox
____

.Internet of Things Vendors
____
Hik Vision, Leviton
____

.Medical Devices
____
Hospira Drug Infusion Pump
____

The above device is listed here based on this
http://hextechsecurity.com/?p=123[recent security research] which outlines
that all of Moose's requirements are met.

The last list below contains vendors that were correlated using the
http://www.urtech.ca/2011/12/default-passwords/[default credentials list] as
previously mentioned but that we were not able to gather information about if
they had Telnet access enabled or not.

____
Ericsson, F5 Networks, Fortinet, Siemens, LSI Corporation, Maxim Integrated, Accelerated Network, Quantum, Advantek, Airtel, AirTies, Radware, Ubee Interactive, AOC, Applied Innovations, Arescom, ARtem, Asante, Ascend, ATL, Atlantis, AVM, Avocent, Axis, Aztech, Bay Networks, Bintec, BMC, Broadlogic, Canyon, Cellit, Ciphertrust, CNet, Compaq, Comtrend, Conceptronic, Conexant, Corecess, CTC Union, Cyclades, Davox, Demarc, Digicom, Draytek, Dynalink, E-Con, Efficient, Everfocus, Flowpoint, Gericom, IBM, iDirect, Inchon, Infacta, Infoblox, INOVA, Interbase, Intermec, Intracom, JD Edwards, Kasda, KTI, Lantronix, Laxo, LG, Livingston, Marconi, McAfee, McData, Mentec, Micronet, Milan, Motorola, Mro software, Netopia, Netport, Netscreen, Netstar, Niksun, Nokia, NOMADIX, Olitec(trendchip), OpenConnect, Osicom, Overland, Ovislink, Pansonic, Phoenix, Pirelli, Planet, Ptcl, QLogic, Quintum Technologies, RM, RoamAbout, Sagem, Samsung, Server TechnologyPower, Sharp, Signamax, Siips, Silex Technology, Simple Smdr, Sitecom, Smartswitch, SMC, Sonic-X, Spectra Logic, SpeedXess, Sphairon, SSA, Stratacom, Swissvoice, Symbol, System/32, Tandem, Telewell, Telindus, Tellabs, Topsec, Troy, TVT System, U.S. Robotics, Unisys, VASCO, VxWorks, Wang, Weidmüeller, Westell, X-Micro, xd, Xylan, Xyplex, Zebra, ZTE
____

If you have access to any of the hardware listed in this section please mailto:github@eset.com[let
us know]:

* Is Telnet enabled by default?
* Can you login with the default credentials via Telnet?
* What make and model do you have?
* What happens if you type in `sh` and then Enter on the default prompt?
