= README
:source-highlighter: pygments

== Router Check Tool

We produced a small tool that can help check whether a router is vulnerable to
Linux/Moose infection mechanism. To do so it verifies if Telnet is enabled and
if the username and password configured on your router is in the list that
Moose carries. This enables you to assess quickly if you could be infected by
this threat or not.

== Usage instructions

=== Linux

Make sure you have a Python 2.7.x interpreter and your `/proc/` filesystem
mounted. Run:

    python moose_router_check.py

=== Mac OS X

Most Mac OS X versions come with a Python 2.7.x interpreter. You don't need
anything. Open a terminal window and navigate to the directory where you
downloaded the Python script. Then execute the following command:

    python moose_router_check.py

=== Windows

NOTE: Unfortunately running Python scripts on Windows is not an enjoyable
experience. If you are not familiar with Python we recommend that you ask some
knowledgeable friend for help instead.

You need a Python interpreter installed. Grab the latest 2.7.x version
from https://www.python.org/downloads/[here]. The `netifaces` package is also
required. An installer of this module for Python 2.7 is available
https://pypi.python.org/packages/2.7/n/netifaces/netifaces-0.10.4.win32-py2.7.exe#md5=5cddb5bb1938948585d15f90f5e22b9d[here].

In order to run the script, open a Command prompt by typing `cmd` in the Start
menu. With a command prompt open, navigate to the folder where you downloaded
then Python script and type in the following:

    python moose_router_check.py

Then follow the on-screen instructions.
